### ISSUE TITLE
[FIX] : Add light border to the cards

### ISSUE THREAD

**Issue by SnehaDeshmukh28** [SnehaDeshmukh28/Recipe-Book#1]
add a black border to the cards

**Comment by ezhillragesh** [comment]
Hi @SnehaDeshmukh28  ,

Is it possible to assign this issue to me? I believe I can help in addressing the problem and working towards a solution. 

Looking forward to your response.

Best regards,
Ezhill Ragesh

**Comment by SnehaDeshmukh28** [comment]
Done

**Comment by SnehaDeshmukh28** [comment]
Issue resolved
