### ISSUE TITLE
[FEAT] : Add a Read.me File 

### ISSUE THREAD

**Issue by SnehaDeshmukh28** [SnehaDeshmukh28/Recipe-Book#4]
For Non-Coders 
Add the readme file having description on what the website is.

**Comment by ezhillragesh** [comment]
Hi @SnehaDeshmukh28  ,

Is it possible to assign this issue to me? I believe I can help in addressing the problem and working towards a solution. 

Looking forward to your response.

Best regards,
Ezhill Ragesh

**Comment by SuryaCreatX** [comment]
Can you assign me this issue?

**Comment by SuryaCreatX** [comment]
Can you assign me this issue?

**Comment by kambleprathamesh** [comment]
Heyy sneha will You assign this task to me. seems to be intrested
