### ISSUE TITLE
[FEAT] : Add a footer

### ISSUE THREAD

**Issue by SnehaDeshmukh28** [SnehaDeshmukh28/Recipe-Book#5]
Add a footer to the page

**Comment by ezhillragesh** [comment]
Hi @SnehaDeshmukh28  ,

Is it possible to assign this issue to me? I believe I can help in addressing the problem and working towards a solution. 

Looking forward to your response.

Best regards,
Ezhill Ragesh

**Comment by AviGawande** [comment]
@SnehaDeshmukh28 had a previous experience of working in frontend development in various projects.
Hope you will assign it to me.

**Comment by SnehaDeshmukh28** [comment]
Issue Resolved
