### ISSUE TITLE
[FEAT] : Make navbar bgcolor according to card button color 

### ISSUE THREAD

**Issue by ayusshh19** [SnehaDeshmukh28/Recipe-Book#6]
**Description : -** 
Navbar background color isnt matching with card theme color (#2ecc71) make that according to theme and have some improvement in UI 

Screenshot : - 
![image](https://github.com/SnehaDeshmukh28/Recipe-Book/assets/89308426/91e41336-3521-4865-86c6-ea96beb2e04a)
![image](https://github.com/SnehaDeshmukh28/Recipe-Book/assets/89308426/bb2dde8e-3f26-4ae1-8e5b-bdb2ec2c511c)

Expected outcome : - 

- [ ] Navbar bg color #2ecc71
- [ ] animation on Navbar

**Comment by AviGawande** [comment]
i can fix it @ayusshh19 assigned it to me.

**Comment by mjgirase07** [comment]
What kind of animation do you want on Navbar @ayusshh19 
and I can fix the bg color of the navbar along with that we have to fix the outline color of the search button also
assigned it to me so I can do that

**Comment by mjgirase07** [comment]
![image](https://github.com/SnehaDeshmukh28/Recipe-Book/assets/110486261/e3d792a8-cb03-490d-bd87-7011703f6fed)
You can see the changes
